version: '3.5'

services:

  postgres:
    container_name: paritet_postgres
    build:
      context: ./docker/postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-paritet_main_dev}
    volumes:
      - postgres_data:/data/postgres 
    ports:
      - "${DB_PORT:-5433}:5432" 
    networks:
      - paritet_network 
    restart: unless-stopped

  redis:
    container_name: paritet_redis
    image: redis:7-alpine 
    restart: always
    ports:
      - "6379:6379" 
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - redis_data:/data 
    networks:
      - paritet_network

  pgadmin:
    container_name: paritet_pgadmin
    build:
      context: ./docker/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - paritet_network
    restart: unless-stopped
    depends_on: 
      - postgres

networks:
  paritet_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: