
services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3500/api 
    depends_on:
      - backend 
      - chat-service # Добавляем зависимость от нового сервиса

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    restart: always
    environment:
      PORT: 3500
      # DATABASE_URL: postgresql://legal_portal_user:your_strong_db_password@db:5432/legal_portal_db
      # JWT_SECRET: your_jwt_secret_for_backend
    ports:
      - "3500:3500" 

  # НОВЫЙ СЕРВИС: chat-service
  chat-service:
    build:
      context: ./chat-service # Папка с этим сервисом
      dockerfile: Dockerfile # Dockerfile для этого сервиса
    restart: always
    environment:
      PORT: 3333 # Этот сервис будет слушать на порту 3333
    ports:
      - "3333:3333" # Открываем порт 3333 на хосте

  nginx:
    image: public.ecr.aws/docker/library/nginx:alpine 
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Конфигурация Nginx
    depends_on:
      - frontend
      - backend
      - chat-service # Добавляем зависимость от chat-service