name: "Build and Deploy Backend"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: backend
  SERVICE_SCOPE: backend
  DOCKERFILE_PATH: tooling/docker/nest/Dockerfile
  PRISMA_SCHEMA_PATH: ./apps/backend/prisma/schema.prisma

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Добавляем QEMU для мульти-архитектурной сборки
      - name: Restore Turborepo cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          # Ключ кэша зависит от ОС и package-lock.json.
          # Если lock-файл меняется, кэш сбрасывается.
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.service_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile_path }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service_name }}:latest
          build-args: |
            APP_NAME=${{ matrix.service_name }}
            APP_SCOPE=${{ matrix.service_scope }}
            PRISMA_SCHEMA_PATH=${{ matrix.prisma_schema_path }}
            # Переменные TURBO_* больше не нужны
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Задача деплоя остается без изменений
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_VPS_HOST }}
          username: ${{ secrets.HETZNER_VPS_USER }}
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          command_timeout: 15m
          script: |
            cd ~/paritet
            # Используем ваш секрет CR_PAT
            echo "${{ secrets.CR_PAT }}" | /usr/bin/docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            # Используем docker-compose с дефисом
            /usr/bin/docker-compose pull
            /usr/bin/docker-compose up -d
            /usr/bin/docker image prune -a -f
