name: "Build Docker Image"

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: service-gateway
  SERVICE_SCOPE: service-gateway
  DOCKERFILE_PATH: tooling/docker/nest/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ env.DOCKERFILE_PATH }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:latest
          build-args: |
            APP_NAME=${{ env.SERVICE_NAME }}
            APP_SCOPE=${{ env.SERVICE_SCOPE }}
            TURBO_TOKEN=
            TURBO_TEAMID=
            TURBO_API=
          cache-from: type=gha
          cache-to: type=gha,mode=max
