name: Next.js CI/CD to cPanel

on: # Ось ця секція. Переконайтеся, що вона так і починається.
  push:
    branches:
      - main # Або 'master', якщо ваша гілка називається master

jobs:
  deploy:
# ... весь інший код, який ми вже вставили