name: Next.js CI/CD to cPanel (Full Automation)

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js project
      run: npm run build

    - name: Clear remote deployment directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        script: |
          rm -rf /home/ohkebsmg/public_html/portal/.next || true
          rm -rf /home/ohkebsmg/public_html/portal/public || true
          echo "Remote deployment directory cleared."

    - name: Deploy .next/standalone via SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server_directory: /home/ohkebsmg/public_html/portal/.next/
        local_dir: ./.next/standalone/

    - name: Deploy public/ via SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server_directory: /home/ohkebsmg/public_html/portal/
        local_dir: ./public/

    - name: Deploy package.json via SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server_directory: /home/ohkebsmg/public_html/portal/
        local_dir: ./package.json

    - name: Install production dependencies on cPanel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        script: |
          source /home/ohkebsmg/nodevenv/public_html/portal/20/bin/activate
          cd /home/ohkebsmg/public_html/portal
          npm install --production || { echo "ERROR: npm install --production failed on cPanel."; exit 1; }

    - name: Restart Node.js application on cPanel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        script: |
          /usr/local/bin/ea-nodejs restart-app --path /home/ohkebsmg/public_html/portal/ || { echo "ERROR: Failed to restart Node.js application."; exit 1; }