name: Next.js CI/CD to cPanel (Standalone Build - SFTP Only, No SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Убедитесь, что это соответствует версии на сервере

    - name: Install dependencies (ONLY for build process, not for upload)
      run: npm install --legacy-peer-deps 

    - name: Build Next.js project (standalone output)
      run: npm run build

    # УДАЛЯЕМ ВСЕ, кроме файла .next/standalone/server.js и логов Passenger
    # Этот шаг требует SSH. Если SSH недоступен, вам придется положиться на то,
    # что SFTP-Deploy-Action перезапишет основные файлы, и вручную чистить старые.
    # Так как вы не хотите SSH, этот шаг ЗАКОММЕНТИРОВАН.
    # ПОМНИТЕ: Без полной очистки на сервере могут оставаться старые/ненужные файлы.
    # - name: Clean up remote directory (requires SSH)
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     script: |
    #       rm -rf /home/ohkebsmg/public_html/portal/*
    #       # Возможно, нужно исключить папку с логами Passenger, если она там находится

    # Загружаем ТОЛЬКО содержимое директории .next/standalone/
    # Это самое важное изменение.
    - name: Deploy .next/standalone content via SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Загружаем содержимое .next/standalone/ В КОРЕНЬ вашего приложения на сервере
        server_directory: /home/ohkebsmg/public_html/portal/ 
        local_dir: ./.next/standalone/ # Исходная директория для загрузки
        # FTP-Deploy-Action перезапишет существующие файлы, но НЕ удалит старые, отсутствующие локально.
        # Это может быть проблемой, если структура standalone меняется.

    - name: Final Manual Steps (Restart Node.js App)
      run: |
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "--- Next.js CI/CD: BUILD AND SFTP DEPLOYMENT COMPLETED SUCCESSFULLY! (STANDALONE FILES UPLOADED) ---"
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "ВАШИ ФАЙЛЫ Next.js ЗАВАНТАЖЕНО НА СЕРВЕР (Standalone билд)."
        echo "Папка 'node_modules' не загружалась отдельно, так как она уже включена в Standalone билд."
        echo ""
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "ОБЯЗАТЕЛЬНЫЙ РУЧНОЙ ШАГ НА СЕРВЕРЕ:"
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        echo ""
        echo "ПЕРЕЗАПУСТИТЕ NODE.JS ПРИЛОЖЕНИЕ ЧЕРЕЗ CPANEL ИНТЕРФЕЙС:"
        echo "   Зайдите в cPanel -> 'Настройка Node.js приложений'."
        echo "   Найдите приложение, соответствующее 'workts.com.ua/portal'."
        echo "   Нажмите кнопку 'Перезапустить'."
        echo ""
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "Ваш сайт должен запработать через несколько минут после выполнения этих ручных шагов."
        echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        exit 0